### ISSUE TITLE
Auto-tag node core PR's with sub-system label

### ISSUE THREAD

**Issue by phillipj** [nodejs-github-bot/github-bot#1]
Identifying which sub-system(s) PR's relates to by looking at the files changed. This in turn could be used to automatically add sub-system labels, and possibly /cc the correct people/teams listed in [docs/onboard-extras.md](https://github.com/nodejs/node/blob/master/doc/onboarding-extras.md).

Refs https://github.com/nodejs/node/pull/5710#issuecomment-204793840

**Comment by Qard** [comment]
It might be good to detach the auto-cc from the auto-label so labels added manually could also automatically trigger a bot cc'ing the relevant people.

**Comment by phillipj** [comment]
> It might be good to detach the auto-cc from the auto-label so labels added manually could also automatically trigger a bot cc'ing the relevant people.

Good catch, haven't thought of that before. Thanks 👍

**Comment by Fishrock123** [comment]
closing in favor of #31
