### ISSUE TITLE
repo for testing

### ISSUE THREAD

**Issue by Fishrock123** [nodejs-github-bot/github-bot#10]
I already have a test org for things, so I made a repo over there. I'm going to add labels to it an some basic tap tests so we can easily tests statuses against travis.

https://github.com/TestOrgPleaseIgnore/test-github-bot

cc @phillipj, @williamkapke .. lmk if you want an invite to there to test things

**Comment by williamkapke** [comment]
Awesome, I was just about to start setting up something on [my test org](https://github.com/no-duh). It would be great to use the work you're doing instead (if possible).

I'd need a hook setup to push to https://hookbot.herokuapp.com/hooks/github.

For others that want to contribute to this down the road, it seems like there are a few paths:
1) Give them instructions on how to set up a test org with their own webhooks.
2) Have them ask for access & webhook to TestOrgPleaseIgnore.
3) Have a bot do Option 2 for them (maybe it could also expire hooks after X days)
4) ...?

**Comment by williamkapke** [comment]
Also, I see you're watching that org's repos... if I'm testing there, you'll get a ton of spam! Fair warning heh

**Comment by Fishrock123** [comment]
@williamkapke Currently I'm trying to set that repo up with the same access configuration the nodejs repos have, but I forget exactly how to do that.

I'll unwatch them. I haven't had anyone else on the org so it wasn't a problem previously.

**Comment by phillipj** [comment]
Closing this as using the TestOrgPleaseIgnore is working pretty good atm
