### ISSUE TITLE
Add support for PR updates

### ISSUE THREAD

**Issue by phillipj** [nodejs-github-bot/github-bot#11]
Currently the bot only responds to *created* PR's. Adding support for reporting Travis build status on PR changes (new or forced commits) would be great.

**Comment by phillipj** [comment]
As the webhooks have currently been configured to "send all events", the bot already gets notified about updates, it just ignores them...

https://github.com/nodejs-github-bot/github-bot/blob/master/server.js#L15 would be particularly interresting

**Comment by TheAlphaNerd** [comment]
I'd be up for taking this on if you want to assign it to me. Can potentially hack ion it from 10k feet this afternoon :smile:

**Comment by phillipj** [comment]
@Fishrock123 did you fix updates with your last changes in #15?

**Comment by Fishrock123** [comment]
@phillipj Oh, yes actually: https://github.com/nodejs-github-bot/github-bot/blob/master/scripts/display-travis-status.js#L9-L10

**Comment by Fishrock123** [comment]
Note: I have not tested this with the PR-commenting, only the PR status updates.
