### ISSUE TITLE
Node core auto labeling improvements

### ISSUE THREAD

**Issue by phillipj** [nodejs-github-bot/github-bot#31]
## Low hanging fruits

- [x] `doc/` for doc
- [x] `benchmark/` for benchmark
- [x] `deps/$name` -> $name (libuv, v8, etc)
- [x] `configure`, `*Makefile`, `node.gyp`, `common.gypi` -> `build` (a lot of stuff in tools/ lives here too but not necessarily low hanging fruit)

*To avoid duplicate work on these, please leave a comment if you'd like to give some of these a shot.*

## Challenges

Regarding the `c++` label for any PR that has file changes in `src/`:

> For example, there might be a PR that makes changes to both `lib/net.js` and `src/tcp_wrap.cc`, but the overall net change in `lib/net.js` is substantially greater than that of `src/tcp_wrap.cc`. In that particular case I would normally just tag it with `net` only.

## How to work on this

Its current labels brain is located in [lib/node-labels.js#resolveLabels()](https://github.com/nodejs-github-bot/github-bot/blob/master/lib/node-labels.js#L9). It's even covered by tests [test/node-labels.test.js](https://github.com/nodejs-github-bot/github-bot/blob/master/test/node-labels.test.js).

Refs nodejs/node#6247

**Comment by Fishrock123** [comment]
We may want to blacklist `node_version.h` from the `c++` label if possible: https://github.com/nodejs/node/pull/6383#event-640812288

**Comment by jasnell** [comment]
I've been considering adding a `release` label that we can use to tag release proposals. Would it be easier to key off that instead of blacklisting `node_version.h`?

**Comment by phillipj** [comment]
@Fishrock123 @jasnell fixed it in https://github.com/nodejs-github-bot/github-bot/pull/32 by ignoring `src/node_version.h`

**Comment by phillipj** [comment]
Closing this for now as the originally mentioned labels has been fixed.
