### ISSUE TITLE
Merge bot?

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [nodejs-github-bot/github-bot#36]
I am currently writing a desktop app to merge automatically upon button press after evaluation of the PRs contents. This could be easily applied to a merging bot that reacts to a label. Would that be interesting? Live example of something similar would be https://github.com/k8s-merge-robot

**Comment by Fishrock123** [comment]
I don't think core would be too interested in that right now, if that is what you are wondering?

**Comment by eljefedelrodeodeljefe** [comment]
Yes. Okay, closing then.

**Comment by Fishrock123** [comment]
see https://github.com/nodejs/node/issues/6331

**Comment by Fishrock123** [comment]
(A CLI tool is the best route because of how manual things can get and often do get)
