### ISSUE TITLE
Notify new commits on a PR ?

### ISSUE THREAD

**Issue by targos** [nodejs-github-bot/github-bot#46]
Just saw this on the react project: https://github.com/facebook/react/pull/6896#issuecomment-221983892

**Comment by phillipj** [comment]
I'm +1 on this. IMO it should be done for rebases as well.

One thing that comes to mind though; we should probably include throttling on this from the beginning, by only creating one of these comments per day or so. We wouldn't want to be too noisy with these comments.

**Comment by targos** [comment]
totally. We should also wait a bit after detecting the commit and not comment at all if a human does in the meantime

**Comment by jbergstroem** [comment]
I'm not a fan of it :( I don't use emails so this would just add to notification noise. Perhaps have the bot email people connected to threads somehow?

**Comment by phillipj** [comment]
@jbergstroem ahhh yeah guess that would double the notifications, not nice at all. Looks like we're able to get a hold of the email of all comment authors via the GH API.

**Comment by targos** [comment]
I just received an email from GitHub notifying new commits in a PR I was involved in. Is it a new feature ?

**Comment by TheAlphaNerd** [comment]
@targos it is a new github feature

**Comment by targos** [comment]
That's nice. Then I guess we can close this issue.
